version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ballsquad
    container_name: ballsquad_db_appc
  app:
    image: ofaydn/ballsquad_java_app:latest
    ports:
      - "8081:8080"
    depends_on:
      - db
networks:
  default:
    name: ballsquad_network
    driver: bridge
